-- código #1.1
SELECT DISTINCT
VEN.APELIDO AS VENDEDOR,
(SELECT DISTINCT MET1.PREVREC FROM SNKH.TGFMET MET1
LEFT JOIN SNKH.TGFCAB CAB1 ON CAB1.CODVEND = MET1.CODVEND
WHERE MET1.CODVEND = CAB.CODVEND
AND MET1.CODMETA = 2
AND MONTH(MET1.DTREF) = 08
AND YEAR(MET1.DTREF) = 2017) AS METAS,
((SELECT ISNULL(SUM((ITE.QTDNEG*ITE.VLRUNIT)-ITE.VLRDESC-ITE.VLRREPRED),0)
FROM SNKH.TGFCAB CAB1
LEFT JOIN SNKH.TGFITE ITE (NOLOCK) ON ITE.NUNOTA=CAB1.NUNOTA
LEFT JOIN SNKH.TGFVEN VEN (NOLOCK) ON VEN.CODVEND=CAB.CODVEND
LEFT JOIN SNKH.AD_CANAL CAN (NOLOCK) ON CAN.CODCANAL=VEN.AD_CODCANAL
WHERE CAB1.TIPMOV = 'V'
AND ITE.CODCFO IN
(5102,5119,5403,5405,5551,5922,6102,6108,6110,6119,6403,6404,6922)
AND CAB1.CODVEND=CAB.CODVEND
AND YEAR(CAB1.DTFATUR)= 2017
AND MONTH(CAB1.DTFATUR)= 08) -
(SELECT ISNULL(SUM((ITE.QTDNEG*ITE.VLRUNIT)-ITE.VLRDESC-ITE.VLRREPRED) ,0)
FROM SNKH.TGFCAB CAB1
LEFT JOIN SNKH.TGFITE ITE (NOLOCK) ON ITE.NUNOTA=CAB1.NUNOTA
LEFT JOIN SNKH.TGFVEN VEN (NOLOCK) ON VEN.CODVEND=CAB.CODVEND
LEFT JOIN SNKH.AD_CANAL CAN (NOLOCK) ON CAN.CODCANAL=VEN.AD_CODCANAL
WHERE CAB1.TIPMOV = 'D'
AND CAB1.CODVEND=CAB.CODVEND
AND YEAR(CAB1.DTENTSAI)= 2017
AND MONTH(CAB1.DTENTSAI)= 08)) AS REALIZADO,
(((SELECT ISNULL(SUM((ITE.QTDNEG*ITE.VLRUNIT)-ITE.VLRDESC-ITE.VLRREPRED),0)
FROM SNKH.TGFCAB CAB1
LEFT JOIN SNKH.TGFITE ITE (NOLOCK) ON ITE.NUNOTA=CAB1.NUNOTA
LEFT JOIN SNKH.TGFVEN VEN (NOLOCK) ON VEN.CODVEND=CAB.CODVEND
LEFT JOIN SNKH.AD_CANAL CAN (NOLOCK) ON CAN.CODCANAL=VEN.AD_CODCANAL
WHERE CAB1.TIPMOV = 'V'
AND ITE.CODCFO IN
(5102,5119,5403,5405,5551,5922,6102,6108,6110,6119,6403,6404,6922)
AND CAB1.CODVEND=CAB.CODVEND
AND YEAR(CAB1.DTFATUR)= 2017
AND MONTH(CAB1.DTFATUR)= 08) -
(SELECT ISNULL(SUM((ITE.QTDNEG*ITE.VLRUNIT)-ITE.VLRDESC-ITE.VLRREPRED) ,0)
FROM SNKH.TGFCAB CAB1
LEFT JOIN SNKH.TGFITE ITE (NOLOCK) ON ITE.NUNOTA=CAB1.NUNOTA
LEFT JOIN SNKH.TGFVEN VEN (NOLOCK) ON VEN.CODVEND=CAB.CODVEND
LEFT JOIN SNKH.AD_CANAL CAN (NOLOCK) ON CAN.CODCANAL=VEN.AD_CODCANAL
WHERE CAB1.TIPMOV = 'D'
AND CAB1.CODVEND=CAB.CODVEND
AND YEAR(CAB1.DTENTSAI)= 2017
AND MONTH(CAB1.DTENTSAI)= 08)) /
(SELECT DISTINCT MET1.PREVREC FROM SNKH.TGFMET MET1
LEFT JOIN SNKH.TGFCAB CAB1 ON CAB1.CODVEND = MET1.CODVEND
WHERE MET1.CODVEND = CAB.CODVEND
AND MET1.CODMETA = 2
AND MONTH(MET1.DTREF) = 08
AND YEAR(MET1.DTREF) = 2017)*100) AS ATINGIMENTO,
(SELECT ISNULL(SUM((ITE.QTDNEG*ITE.VLRUNIT)-ITE.VLRDESC-ITE.VLRREPRED),0)
FROM SNKH.TGFCAB CAB1
LEFT JOIN SNKH.TGFITE ITE (NOLOCK) ON ITE.NUNOTA=CAB1.NUNOTA
LEFT JOIN SNKH.TGFVEN VEN (NOLOCK) ON VEN.CODVEND=CAB.CODVEND
LEFT JOIN SNKH.AD_CANAL CAN (NOLOCK) ON CAN.CODCANAL=VEN.AD_CODCANAL
WHERE CAB1.TIPMOV = 'V'
AND ITE.CODCFO IN
(5102,5119,5403,5405,5551,5922,6102,6108,6110,6119,6403,6404,6922)
AND CAB1.CODVEND=CAB.CODVEND
AND YEAR(CAB1.DTFATUR)= 2017
AND MONTH(CAB1.DTFATUR)= 08) AS FATURAMENTO_BRUTO,
(SELECT ISNULL(SUM((ITE.QTDNEG*ITE.VLRUNIT)-ITE.VLRDESC-ITE.VLRREPRED) ,0)
FROM SNKH.TGFCAB CAB1
LEFT JOIN SNKH.TGFITE ITE (NOLOCK) ON ITE.NUNOTA=CAB1.NUNOTA
LEFT JOIN SNKH.TGFVEN VEN (NOLOCK) ON VEN.CODVEND=CAB.CODVEND
LEFT JOIN SNKH.AD_CANAL CAN (NOLOCK) ON CAN.CODCANAL=VEN.AD_CODCANAL
WHERE CAB1.TIPMOV = 'D'
AND CAB1.CODVEND=CAB.CODVEND
AND YEAR(CAB1.DTENTSAI)= 2017
AND MONTH(CAB1.DTENTSAI)= 08) AS DEVOLUCAO
FROM SNKH.TGFCAB CAB
LEFT JOIN SNKH.TGFITE ITE (NOLOCK) ON ITE.NUNOTA=CAB.NUNOTA
LEFT JOIN SNKH.TGFVEN VEN (NOLOCK) ON VEN.CODVEND=CAB.CODVEND
LEFT JOIN SNKH.AD_CANAL CAN (NOLOCK) ON CAN.CODCANAL=VEN.AD_CODCANAL
LEFT JOIN SNKH.TGMMET MET (NOLOCK) ON MET.CODVEND = cAB.CODVEND
ORDER BY 1,2