TRUNCATE TABLE [Report_SalesForce_Criacao_Manual]

INSERT INTO [Report_SalesForce_Criacao_Manual]
SELECT
	   [ID_da_oportunidade]
      ,[Proprietário_da_oportunidade]
      ,CONVERT(DATE,[Data_da_última_mudança_de_fase], 103) [Data_da_última_mudança_de_fase]
      ,CONVERT(DATE,[Data_da_última_modificação], 103) [Data_da_última_modificação]
      ,[Cliente_Estratégico]
      ,[Nome_da_conta]
      ,[Nome_da_oportunidade]
      ,[Fase]
      ,[Motivo_da_perda]
      ,[Gestor]
      ,[Gestor_2]
      ,[Probabilidade_(%)]
      ,[Tipo_Agente]
      ,[Duração]
	  ,CONVERT(DATE,[Data_de_fechamento], 103) [Data_de_fechamento]
      ,CONVERT(DATE,[Data_de_criação], 103) [Data_de_criação]
      ,[Próxima_etapa]
      ,[Origem_do_lead]
      ,[Tipo]
      ,[Moeda_da_oportunidade]
      ,[Criado_por]
      ,[Modificado_pela_última_vez_por]
      ,[Valor_Moeda]
      ,CONVERT(DECIMAL,REPLACE([Valor_(convertido)],',','.')) [Valor_(convertido)]
	  ,CONVERT(DATE,[Última_atividade], 103) [Última_atividade]
      ,[Tem_produtos]
      ,[Alias_de_criação]
      ,[Valor_(convertido)_Moeda]
      ,CONVERT(DECIMAL,REPLACE([Valor_(convertido)],',','.')) [Valor_(convertido)]
      ,[Fechado]
      ,[Ganhos]
      ,[Duração_da_fase]
      ,[Proprietário_da_conta]
      ,[Tipo_de_conta]
      ,[Autoprodução]
      ,[Cross_Selling]
      ,[Tipo_de_Oportunidade]
      ,[Origem_da_Oportunidade]
      ,[Nome_da_Consultoria]
      ,[Cotação_em_andamento]
      ,[Cotações]
      ,[Loss_Reason]
      ,[Nome_Consultor]
      ,[N°_Proposta_Oportunidade]
      ,[CNPJ]
      ,[Credit_Rating]
      ,[Credit_Rating_2]
      ,[Origem]
      ,[Demanda_contratada_(KW)]
      ,[ID_da_conta]
      ,[Produto_da_Oportunidade]
      ,[Descrição]
      ,[Descrição_da_conta]
      ,[Origem_da_Oportunidade_2]
      ,[Origem_Relatório]
      ,[Origem_da_campanha_principal]
      ,[Origem_2]
      ,[Origem_Relatório_2]
  FROM [AdventureWorks2022].[dbo].[Report_SalesForce_Criacao_Automatica]
